# Change these first
owner: chris9091 # Your GitHub organization or username, where this repository lives
repo: Fleksa-Monitor # The name of this repository

sites:
  - name:	Indian Curry House Ostend
    url:	http://indiancurryhouseostend.de
  - name:	Taste of India Frankfurt
    url:	http://tasteofindia-ffm.de
  - name:	Desi Adda
    url:	http://desiadda.de
  - name:	Smart Pizza Offenbach
    url:	http://smartpizzas.de
  - name:	Pizzeria O Sole Mio
    url:	http://bochum-osolemio.de
  - name:	Alt Bockenheim - Crazy Pizza
    url:	http://restaurantcrazypizza.de
  - name:	Alt Bockenheim - Indian Restaurant
    url:	http://restaurantaltbockenheim.de
  - name:	Food World
    url:	http://offenbach-foodworld.de
  - name:	Indian Curry House Niederrad
    url:	http://indiancurryhouseniederrad.de
  - name:	Restaurant Mai Vien
    url:	http://maivien.fleksa.de
  - name:	Restaurant Taj Mahal
    url:	http://frechentajmahal.de
  - name:	Indian food Company
    url:	http://indianfood-company.de
  - name:	Restaurant Isha
    url:	http://isha-restaurant.de
  - name:	Ganesha Tandoori
    url:	http://ganeshafrankfurt.de
  - name:	Punjab Garden Tandoori
    url:	http://punjabgardenfrankfurt.de
  - name:	Sushi Sensei Frankfurt
    url:	http://sushisenseifrankfurt.de
  - name:	Pizzeria Bella Italia
    url:	http://pizzabellaitaliafrankfurt.de
  - name:	Pizza Kaiser
    url:	http://pizzakaiser-frankfurt.de
  - name:	Delhi Tandoori
    url:	http://delhitandoori.de
  - name:	Pizza Eck Frankfurt
    url:	http://pizza-eck-frankfurt.de
  - name:	Pizzeria Mülheim 2
    url:	http://xn--pizzeriamlheim2-7vb.de
  - name:	Restaurant Nidda
    url:	http://restaurant-nidda.de
  - name:	Bali's Restaurant
    url:	http://balisrestaurant-ob.de
  - name:	Pizza Hamburger Inn
    url:	http://pizzahamburgerinn-griesheim.de
  - name:	Uno's Pizza
    url:	http://pizzeriaunoffm.de
  - name:	Restaurant Ashoka Frankfurt
    url:	http://ashokafrankfurt.de
  - name:	Good Taste
    url:	http://goodtaste.fleksa.de
  - name:	Restaurant Hanoi Quan
    url:	http://hanoiquanfrankfurt.de
  - name:	Tandoori Masala Imbiss
    url:	http://tandoorimasalaimbiss.de
  - name:	Restaurant Kashmir India
    url:	http://restaurantkashmirindia.de
  - name:	Bali's Restaurant
    url:	http://balisrestaurant-wesel.de
  - name:	Go eat food service
    url:	http://goeatfrankfurt.de
  - name:	Star Pizza Deggendorf
    url:	http://star-pizza-deggendorf.de
  - name:	Main Curry House
    url:	http://main-curry-house.de
  - name:	Pizza Haus
    url:	http://pizzahauslandau.de
  - name:	Restaurant Little India
    url:	http://littleindiaalteglofsheim.de
  - name:	Pizza Plattlinger
    url:	http://pizzaplattlinger.de
  - name:	Pizza Roma Dingolfing
    url:	http://pizzaromadingolfing.de
  - name:	Pizza Roma Wallersdorf
    url:	http://pizzaromawallersdorf.de
  - name:	Pizza La Fontana
    url:	http://altdorflafontana.de
  - name:	Restaurant Taj Mahal
    url:	http://altdorftajmahal.de
  - name:	Restaurant Little India
    url:	http://littleindiafreudenstadt.de
  - name:	Restaurant Namaste
    url:	http://namasteplattling.de
  - name:	Star Pizzaservice
    url:	http://teisnachstarpizza.de
  - name:	Roma Pizza Schierling
    url:	http://pizzaromaschierling.de
  - name:	Kabab House Offenbach
    url:	http://kababhouse.de
  - name:	Restaurant Mayuri
    url:	http://mayuri-duisburg.de
  - name:	India Haus Restaurant
    url:	http://indiahaus-md.de
  - name:	Spice of India
    url:	http://spiceofindia-hattersheim.de
  - name:	Restaurant Mai Pho
    url:	http://maiphokronberg.de
  - name:	Pizzeria Marco Polo
    url:	http://marcopolo-aussernzell.de
  - name:	Restaurant Sahaj
    url:	http://restaurant-sahaj.de
  - name:	Pizza Mattu Osterhofen
    url:	http://mattupizzaosterhofen.de
  - name:	Badal's Küche
    url:	http://xn--badalskche-geb.de
  - name:	Restaurant India Gate
    url:	http://indiagateeggenfelden.de
  - name:	Rana's Pizza und Döner Service
    url:	http://rubipizzaservice.de
  - name:	Taj Mahal Restaurant
    url:	http://tajmahaldeggendorf.de
  - name:	Pizza Heimservice Taufkirchen
    url:	http://pizzataufkirchen.de
  - name:	Restaurant Namaskar
    url:	http://namaskarrestaurant.de
  - name:	Restaurant Jannat
    url:	http://restaurant-jannat.de
  - name:	Nano Pizza Heimservice
    url:	http://nanopizza.de
  - name:	Tar Pizzaservice
    url:	http://tarpizzaservice.de
  - name:	Pizzaservice Pizzano
    url:	http://pizzaservicepizzano.de
  - name:	BLITZ CITY (Pizzaservice u. Lieferservice)
    url:	http://pizzablitzcity.com
  - name:	Indian Zaika - Indisches restaurant
    url:	http://zaikarestaurant.de
  - name:	Indian Tandoori Restaurant
    url:	http://indiantandoorirestaurant.de
  - name:	Pizza Harmonie
    url:	http://pizzaharmonie.de
  - name:	Pizza Service Schwandorf
   url:	http://pizzaschwandorf.de
  - name:	Harman Pizza
   url:	http://harmanpizzapliening.de
  - name:	Frankfurter Schnitzelexpress
   url:	http://schnitzelheimservice.de
  - name:	India Gate Sossenheim
   url:	http://indiagatefrankfurt.de
  - name:	Restaurant India Gate
   url:	http://indiagatestraubing.de
  - name:	The Taj Neubiberg
   url:	http://tajamcampeon.de
  - name:	Indian Tandoori Restaurant
   url:	http://restaurantindiantandoori.de
  - name:	Cafe Restaurant Maritimes
   url:	http://maritimesroding.de
  - name:	Pizza Roma Köz
   url:	http://xn--pizzabadktzting-htb.de
  - name:	Indian Tandoori Kitchen
   url:	http://indiantandoorikitchen.de
  - name:	Deli Tadka
   url:	http://delitadka.de
  - name:	Natraj Indisches Restaurant
   url:	http://xn--natrajmnchen-jlb.de
  - name:	Restaurant Sangam
   url:	http://xn--sangammnchen-jlb.de
  - name:	Restaurant Suhag
   url:	http://restaurantsuhag.de
  - name:	DHABA Schwabing West
   url:	http://xn--dhabamnchen-yhb.de
  - name:	Restaurant Masala
   url:	http://xn--masalamnchen-jlb.de
  - name:	Ristorante Pizzeria Mediterraneo
   url:	http://mediterraneokelsterbach.de
  - name:	Mini Punjab
   url:	http://minipunjab.de
  - name:	Indian Restaurant Rajdarbaar Tandoori
   url:	http://xn--rajdarbaar-dsseldorf-0ec.de
  - name:	Pizza Town Dieburg
   url:	http://pizzatown-dieburg.de
  - name:	Express Pizza
   url:	http://xn--pizzaexpresshchstadt-gbc.de
  - name:	Der Pizzaservice Straubing
   url:	http://straubingpizzaservice.de
  - name:	Restaurant Tonino
   url:	http://tonino-karlsfeld.de
  - name:	Tadsch Mahal (Taj Mahal)
   url:	http://xn--tajmahalnrnberg-7vb.de
  - name:	Pizza Peperoni
   url:	http://peperonihessdorf.de
  - name:	Döner Pizza am Ronhof
   url:	http://xn--dnerpizzaronhof-8sb.de
  - name:	Restaurant Roter Adler (Dallizza)
   url:	http://restaurantroteradler.de
  - name:	Deli Tadka
   url:	http://pasing.delitadka.de
  - name:	Deli Tadka
   url:	http://riem.delitadka.de
  - name:	Deli Tadka
   url:	http://pep.delitadka.de
  - name:	Food world - Indian Kitchen
   url:	http://indiankitchenoffenbach.de
  - name:	Pizza Roma Passau
   url:	http://pizzaromapassau.de
  - name:	Der Pizzaservice Passau
   url:	http://pizzaservicepassau.de
  - name:	Restaurant Ganesha
   url:	http://xn--ganeshamnchen-3ob.de
  - name:	Pizza Bert Passau
   url:	http://pizza-bert.de
  - name:	Pizza Romana
   url:	http://romanaaidenbach.de
  - name:	Nano Pizza Heimservice
   url:	http://nanopizza-ergoldsbach.de
  - name:	Restaurant Kohinoor
   url:	http://xn--kohinoornrnberg-7vb.de
  - name:	Restaurant Shiva
   url:	http://xn--restaurantshivafrth-lbc.de
  - name:	Maharaja Palace
   url:	http://xn--maharaja-palace-nrnberg-spc.de
  - name:	Restaurant Maharaja
   url:	http://maharajaroth.de
  - name:	Robertino's Nürnberger Pizzaservice
   url:	http://xn--nrnberger-pizzaservice-slc.de
  - name:	Restaurant Maharaja
   url:	http://ansbach-maharaja.de
  - name:	Restaurant Gandhi
   url:	http://gandhirestaurant.de
  - name:	Taste of India
   url:	http://tasteofindiaeppertshausen.de
  - name:	Restaurant Shagun
   url:	http://xn--shagunmnchen-jlb.de
   name:	Curry House Erlangen
   url:	http://erlangener-curryhouse.de
   name:	Bahia Pizzaservice
   url:	http://bahiapizza-herzogenaurach.de
   name:	Pizza 2 Night Babenhausen
   url:	http://pizza2night-babenhausen.de
   name:	Bistro serVus München
   url:	http://xn--bistroservus-mnchen-jbc.de
   name:	Optimal Pizza
   url:	http://xn--optimalpizza-mnchen-jbc.de
   name:	Punjabi Pizza Putzbrunn
   url:	http://punjabipizza-putzbrunn.de
   name:	Pizza Center Mering
   url:	http://pizzacenter-mering.de
   name:	Salaam Namaste
   url:	http://salaamnamaste-teisnach.de
   name:	Pizza Center Neusäß
   url:	http://xn--pizzacenter-neusss-0tb.de
   name:	Indisch Curry Masala
   url:	http://currymasala-grossaitingen.de
   name:	City Burgerhaus u. Hot Dog
   url:	http://cityburgerhaus-langerringen.de
   name:	Pizza Service Hiltenfingen
   url:	http://hiltenfingen-pizzaservice.de
   name:	Pizzaservice Laguna
   url:	http://xn--pizzalaguna-neusss-0tb.de
   name:	Royal India - Indisches Restaurant
   url:	http://xn--royalindia-badwrishofen-mlc.de
   name:	Pizza Riem - Indischer Curry
   url:	http://pizzariem-indischercurry.de
   name:	Pizza Taxi
   url:	http://garching-pizzataxi.de
   name:	Tanda Palace
   url:	http://tandaexpress.de
   name:	Amico Pizza & Burger
   url:	http://pizzaamico-oberschleissheim.de
   name:	Der Pizzaservice Hohenthann
   url:	http://derpizza-hohenthann.de
   name:	Der Pizzaservice Landshut
   url:	http://derpizza-landshut.de
   name:	Mini Punjab Dine-in
   url:	http://minipunjab.fleksa.de
   name:	Eli's Pizza & Pasta
   url:	http://xn--elis-pizza-mnchen-e3b.de
   name:	Restaurant Bollywood
   url:	http://bollywood-schongau.de
   name:	Ekam Bollywood
   url:	http://restaurant-ekam.de
   name:	Raj Mahal
   url:	http://rajmahal-regensburg.de
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Fleksa-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
